#!/usr/bin/env node
/* Builds the installable ESM package of the components into dist/react/.

     node tools/build-package.mjs

   What it writes (dist/ is gitignored, so none of this is committed):

     dist/react/<group>/<Name>.js     each system/components/<group>/<Name>.jsx,
                                      compiled with the same Babel setup as
                                      tools/build-bundle.mjs. It stays an ES
                                      module that does `import React from
                                      "react"`, so React is the consumer's.
     dist/react/<group>/<Name>.d.ts   the hand-written declarations, copied
     dist/react/index.js              re-exports every export of every file
     dist/react/index.d.ts            re-exports every .d.ts
   dist/styles.css                  system/styles.css with every local @import
                                    inlined, recursively and in order, with one
                                    "from <path>" comment marker per file. It
                                    makes no network request of its own.
   dist/fonts.css                   the @imports of external URLs (the Google
                                    Fonts stylesheets), once each. They can't
                                    be inlined, and a third-party request is
                                    the consumer's choice, so they ship apart
                                    as the opt-in "@dovetail-ds/react/fonts.css".

   dist/configure/core.js           the docs site's Configure panel without its
                                    page: assets/configure-data.js and
                                    assets/theme.js wrapped in one ES module
                                    that runs them headless and exports what
                                    the panel computes (css, vars, fontHref,
                                    checks, choices, defaults). The Claude
                                    Code skill in skills/dovetail-theme uses
                                    it, so a theme written from answers is the
                                    same file Configure's Download gives. Not
                                    in the exports map: it is the skill's, not
                                    public API.

   dist/tokens/ (tokens.css, tokens.json, tokens.d.ts) is written by the token
   build, not here; package.json only maps "./tokens/*" onto it.

   Relative import specifiers ending in .jsx are rewritten to .js by a small
   Babel plugin, in the compiled code and in the declarations alike. The
   exports come from each source's AST and are cross-checked against
   system/manifest.json; a difference is a warning, not a failure.

   system/components/lib (vendored React), bundle.js, bundle.css and the .md
   files are not part of the package.

     node tools/build-package.mjs --out <dir>

   writes just the components (the dist/react/ part) into <dir> instead, and
   leaves dist/ alone: a check that runs beside another one building the
   package gets a copy nobody else rebuilds under it. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformSync } from "@babel/core";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "system", "components");
const OUT = path.join(ROOT, "dist", "react");
const MANIFEST = path.join(ROOT, "system", "manifest.json");
const STYLES_SRC = path.join(ROOT, "system", "styles.css");
const STYLES_OUT = path.join(ROOT, "dist", "styles.css");
const FONTS_OUT = path.join(ROOT, "dist", "fonts.css");
const CONFIGURE_OUT = path.join(ROOT, "dist", "configure", "core.js");

const REACT = [["@babel/preset-react", { runtime: "classic" }]];
const HEADER = "/* Generated by tools/build-package.mjs from system/components. Do not edit. */\n";

/* Rewrites "./X.jsx" and "../g/X.jsx" to ".js" wherever a module specifier
   appears. Each rewrite is reported through onRewrite, so a caller that wants
   the original text untouched can splice by position instead of reprinting. */
function rewriteJsxSpecifiers(onRewrite = () => {}) {
  const fix = (lit) => {
    if (!lit || typeof lit.value !== "string") return;
    const v = lit.value;
    if (!/^\.\.?\//.test(v) || !v.endsWith(".jsx")) return;
    const next = v.slice(0, -".jsx".length) + ".js";
    onRewrite(lit, next);
    lit.value = next;
    if (lit.extra) lit.extra = { ...lit.extra, rawValue: next, raw: JSON.stringify(next) };
  };
  return () => ({
    name: "rewrite-jsx-specifiers",
    visitor: {
      "ImportDeclaration|ExportNamedDeclaration|ExportAllDeclaration"(p) {
        fix(p.node.source);
      },
      CallExpression(p) {
        if (p.node.callee.type === "Import" && p.node.arguments[0]?.type === "StringLiteral") fix(p.node.arguments[0]);
      },
      ImportExpression(p) {
        if (p.node.source?.type === "StringLiteral") fix(p.node.source);
      },
      TSImportType(p) {
        /* Babel 8 calls it source; Babel 7 wrapped it in argument. */
        const arg = p.node.source ?? p.node.argument;
        fix(arg?.type === "TSLiteralType" ? arg.literal : arg);
      },
      TSExternalModuleReference(p) {
        fix(p.node.expression);
      },
    },
  });
}

/* Collects the names a module exports, and whether it has a default export. */
function collectExports(into) {
  return () => ({
    name: "collect-exports",
    visitor: {
      ExportNamedDeclaration(p) {
        const { declaration: d, specifiers } = p.node;
        if (d) {
          if (d.type === "VariableDeclaration") for (const v of d.declarations) into.names.push(...idsOf(v.id));
          else if (d.id) into.names.push(d.id.name);
        }
        for (const s of specifiers) if (s.exported) into.names.push(s.exported.name ?? s.exported.value);
      },
      ExportDefaultDeclaration() {
        into.hasDefault = true;
      },
      ExportAllDeclaration(p) {
        into.starFrom.push(p.node.source.value);
      },
    },
  });
}

function idsOf(pattern) {
  if (!pattern) return [];
  switch (pattern.type) {
    case "Identifier": return [pattern.name];
    case "ObjectPattern": return pattern.properties.flatMap((pr) => idsOf(pr.type === "RestElement" ? pr.argument : pr.value));
    case "ArrayPattern": return pattern.elements.flatMap(idsOf);
    case "AssignmentPattern": return idsOf(pattern.left);
    case "RestElement": return idsOf(pattern.argument);
    default: return [];
  }
}

/* Whether a component module has to run on the client, which is what a
   "use client" directive tells a React Server Components bundler. True when
   the module calls a hook or createContext, reads window, document or
   navigator, or hands an event handler it made itself to an element, e.g.
   onClick={() => setOpen(true)}. A handler passed straight through from props
   (onClick={onClick}) doesn't count: a server component can render that. When
   in doubt it says true, which only costs server rendering, never breaks it. */
const BROWSER_GLOBALS = new Set(["window", "document", "navigator"]);
function needsClient(src, filename) {
  let client = false;
  transformSync(src, {
    filename,
    parserOpts: { plugins: ["jsx"] },
    plugins: [
      () => ({
        visitor: {
          MemberExpression(p) {
            const { object: o, property: k } = p.node;
            if (o.type === "Identifier" && o.name === "React" && k.type === "Identifier" && /^(use[A-Z]\w*|createContext)$/.test(k.name)) client = true;
          },
          CallExpression(p) {
            const c = p.node.callee;
            if (c.type === "Identifier" && /^use[A-Z]/.test(c.name)) client = true;
          },
          Identifier(p) {
            if (BROWSER_GLOBALS.has(p.node.name) && p.isReferencedIdentifier() && !p.scope.hasBinding(p.node.name)) client = true;
          },
          JSXAttribute(p) {
            const { name, value } = p.node;
            if (name.type !== "JSXIdentifier" || !/^on[A-Z]/.test(name.name) || value?.type !== "JSXExpressionContainer") return;
            const e = value.expression;
            if (e.type === "MemberExpression" || e.type === "JSXEmptyExpression") return;
            if (e.type === "Identifier" && (e.name === "undefined" || p.scope.getBinding(e.name)?.kind === "param")) return;
            client = true;
          },
        },
      }),
    ],
    configFile: false,
    babelrc: false,
    code: false,
    sourceType: "module",
  });
  return client;
}

/* JSX component names a module uses without importing or defining them. The
   docs site's bundle puts every component in one scope, so a missing import
   works there and only breaks in the package, where each module stands alone
   (a Navbar rendering <Drawer> without importing it throws once it collapses). */
function undeclaredComponents(src, filename) {
  const missing = new Set();
  transformSync(src, {
    filename,
    parserOpts: { plugins: ["jsx"] },
    plugins: [
      () => ({
        visitor: {
          JSXOpeningElement(p) {
            let n = p.node.name;
            while (n.type === "JSXMemberExpression") n = n.object;
            if (n.type === "JSXIdentifier" && /^[A-Z]/.test(n.name) && !p.scope.hasBinding(n.name)) missing.add(n.name);
          },
        },
      }),
    ],
    configFile: false,
    babelrc: false,
    code: false,
    sourceType: "module",
  });
  return [...missing];
}

/* Every .jsx under system/components/<group>/, skipping the vendored lib. */
function sourceFiles() {
  const out = [];
  for (const group of fs.readdirSync(SRC, { withFileTypes: true })) {
    if (!group.isDirectory() || group.name === "lib") continue;
    for (const f of fs.readdirSync(path.join(SRC, group.name))) {
      if (f.endsWith(".jsx")) out.push(`${group.name}/${f}`);
    }
  }
  return out.sort();
}

function compileSource(rel) {
  const src = fs.readFileSync(path.join(SRC, rel), "utf8");
  const exp = { names: [], hasDefault: false, starFrom: [] };
  const code = transformSync(src, {
    filename: path.join(SRC, rel),
    presets: REACT,
    plugins: [rewriteJsxSpecifiers(), collectExports(exp)],
    configFile: false,
    babelrc: false,
    comments: true,
    sourceType: "module",
  }).code;
  return { code, exp, client: needsClient(src, path.join(SRC, rel)) };
}

/* Declarations are copied byte for byte except for the specifiers the plugin
   rewrites, which are spliced in by position, so JSDoc and layout survive. */
function copyDeclaration(rel) {
  const src = fs.readFileSync(path.join(SRC, rel), "utf8");
  const edits = [];
  const exp = { names: [], hasDefault: false, starFrom: [] };
  transformSync(src, {
    filename: path.join(SRC, rel),
    parserOpts: { plugins: [["typescript", { dts: true }]] },
    plugins: [
      rewriteJsxSpecifiers((lit, next) => {
        const q = src[lit.start];
        edits.push([lit.start, lit.end, q + next + q]);
      }),
      collectExports(exp),
    ],
    configFile: false,
    babelrc: false,
    code: false,
    sourceType: "module",
  });
  let out = src;
  for (const [s, e, text] of edits.sort((a, b) => b[0] - a[0])) out = out.slice(0, s) + text + out.slice(e);
  return { code: out, exp, rewrites: edits.length };
}

/* Exports that exist so one component file can share a piece with another,
   not for consumers. They stay in their own module (Cover and Video import
   UploadFrame from Image; Drawer imports useModalFocus from Dialog; Navbar
   and Drawer import fillTone from Section) but are
   left out of index.js, so they are not public API that a later refactor
   would break. */
const INTERNAL = new Set(["UploadFrame", "useModalFocus", "fillTone"]);

/* Inlines every local @import of a stylesheet, depth first, in source order,
   which is the order the browser would apply them. External URLs are collected
   into `externals` and dropped from the body; the caller writes them to
   dist/fonts.css, since a remote stylesheet can't be inlined. Comments are skipped, so a
   comment that mentions @import is left alone. An import with a media, layer or
   supports condition cannot be flattened without changing meaning, so it throws
   rather than guess. */
const CSS_TOKEN =
  /\/\*[\s\S]*?\*\/|@import\s+(?:url\(\s*(?:"([^"]*)"|'([^']*)'|([^)\s]*))\s*\)|"([^"]*)"|'([^']*)')\s*([^;]*);/g;
const CSS_URL = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)\s]*))\s*\)/g;
const IS_ABSOLUTE = /^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i;

function inlineCss(file, state, stack = []) {
  const rel = path.relative(ROOT, file).split(path.sep).join("/");
  if (stack.includes(file)) {
    throw new Error(`${rel}: @import cycle: ${[...stack, file].map((f) => path.relative(ROOT, f)).join(" -> ")}`);
  }
  const src = fs.readFileSync(file, "utf8");
  state.files.push(rel);
  let body = "";
  let last = 0;
  for (const m of src.matchAll(CSS_TOKEN)) {
    if (m[0].startsWith("/*")) continue;
    const spec = m[1] ?? m[2] ?? m[3] ?? m[4] ?? m[5];
    const cond = m[6].trim();
    body += src.slice(last, m.index);
    last = m.index + m[0].length;
    if (IS_ABSOLUTE.test(spec)) {
      const line = `@import url("${spec}")${cond ? " " + cond : ""};`;
      if (!state.externals.includes(line)) state.externals.push(line);
      continue;
    }
    if (cond) throw new Error(`${rel}: @import "${spec}" has a condition (${cond}), which cannot be inlined`);
    const target = path.resolve(path.dirname(file), spec);
    if (!fs.existsSync(target)) throw new Error(`${rel}: @import "${spec}" does not exist`);
    body += inlineCss(target, state, [...stack, file]);
  }
  body += src.slice(last);
  /* A relative url() in a rule would resolve against dist/ once inlined. */
  const rules = body.replace(/\/\*[\s\S]*?\*\//g, "");
  for (const u of rules.matchAll(CSS_URL)) {
    const v = u[1] ?? u[2] ?? u[3];
    if (v && !IS_ABSOLUTE.test(v)) state.warnings.push(`${rel}: url(${v}) is relative, and would resolve against dist/ once inlined`);
  }
  return `/* from ${rel} */\n${body.trim()}\n\n`;
}

function buildStyles(warn) {
  const state = { files: [], externals: [], warnings: [] };
  const body = inlineCss(STYLES_SRC, state);
  for (const w of state.warnings) warn(w);
  const css = "/* Generated by tools/build-package.mjs from system/styles.css. Do not edit. */\n\n" + body;
  const fonts =
    "/* Generated by tools/build-package.mjs from the font @imports in system/styles.css. Do not edit.\n" +
    "   Loads the typefaces from Google Fonts. Import it before styles.css, or leave it out and\n" +
    "   self-host the fonts under the same family names. */\n" +
    state.externals.join("\n") + "\n";
  const bare = css.replace(/\/\*[\s\S]*?\*\//g, "");
  if (/@import\b/.test(bare)) throw new Error("dist/styles.css has an @import that was not inlined");
  for (const line of state.externals) {
    if (!/^@import url\("(?:https?:)?\/\//i.test(line)) throw new Error(`dist/fonts.css would import ${line}`);
  }
  fs.mkdirSync(path.dirname(STYLES_OUT), { recursive: true });
  fs.writeFileSync(STYLES_OUT, css);
  fs.writeFileSync(FONTS_OUT, fonts);
  return { files: state.files.length, externals: state.externals, bytes: Buffer.byteLength(css) };
}

/* The two browser scripts share a `window`, so a local one stands in for it:
   the data file assigns to it, and theme.js finds DovetailThemeHeadless on it
   and returns its pure part before touching the page. A consumer's real
   window is never read or written, in a browser or anywhere else. */
function buildConfigureCore() {
  const data = fs.readFileSync(path.join(ROOT, "assets", "configure-data.js"), "utf8");
  const theme = fs.readFileSync(path.join(ROOT, "assets", "theme.js"), "utf8");
  const out =
    "/* Generated by tools/build-package.mjs from assets/configure-data.js and assets/theme.js. Do not edit. */\n" +
    "const window = { DovetailThemeHeadless: true };\n\n" +
    data + "\n" + theme + "\n" +
    "const core = window.DovetailThemeCore;\n" +
    "if (!core) throw new Error(\"assets/theme.js did not hand over its headless core\");\n" +
    "export const { defaults, choices, data, css, vars, fontHref, checks } = core;\n";
  fs.mkdirSync(path.dirname(CONFIGURE_OUT), { recursive: true });
  fs.writeFileSync(CONFIGURE_OUT, out);
  return Buffer.byteLength(out);
}

function main(dir = OUT) {
  const warnings = [];
  const warn = (msg) => warnings.push(msg);

  fs.rmSync(dir, { recursive: true, force: true });

  const files = sourceFiles();
  const owners = new Map();
  const modules = [];
  let clientCount = 0;

  for (const rel of files) {
    const base = rel.slice(0, -".jsx".length);
    const src = fs.readFileSync(path.join(SRC, rel), "utf8");
    const missing = undeclaredComponents(src, path.join(SRC, rel));
    if (missing.length) throw new Error(`${rel} renders ${missing.map((n) => `<${n}>`).join(", ")} without importing it`);
    const { code, exp, client } = compileSource(rel);
    if (client) clientCount++;
    if (exp.hasDefault) warn(`${rel}: has a default export, which index.js does not re-export`);
    if (exp.starFrom.length) warn(`${rel}: has export * from ${exp.starFrom.join(", ")}, which index.js does not follow`);
    for (const n of exp.names) {
      if (owners.has(n)) warn(`${n} is exported by both ${owners.get(n)} and ${rel}; index.js keeps the first`);
      else owners.set(n, rel);
    }

    fs.mkdirSync(path.dirname(path.join(dir, base)), { recursive: true });
    fs.writeFileSync(path.join(dir, `${base}.js`), HEADER + (client ? '"use client";\n' : "") + code + "\n");

    const dts = `${base}.d.ts`;
    let declared = null;
    if (fs.existsSync(path.join(SRC, dts))) {
      const d = copyDeclaration(dts);
      fs.writeFileSync(path.join(dir, dts), d.code);
      declared = new Set(d.exp.names);
    } else {
      warn(`${rel}: no ${path.basename(dts)} beside it`);
    }
    for (const n of exp.names) {
      if (INTERNAL.has(n)) continue;
      if (declared && !declared.has(n)) warn(`${n} (${rel}) is exported at runtime but not declared in ${path.basename(dts)}`);
    }
    modules.push({ base, names: exp.names.filter((n) => owners.get(n) === rel && !INTERNAL.has(n)), hasDts: !!declared });
  }

  const js = modules
    .filter((m) => m.names.length)
    .map((m) => `export { ${m.names.join(", ")} } from "./${m.base}.js";`);
  fs.writeFileSync(path.join(dir, "index.js"), HEADER + js.join("\n") + "\n");

  const dtsLines = modules.filter((m) => m.hasDts).map((m) => `export * from "./${m.base}.js";`);
  fs.writeFileSync(path.join(dir, "index.d.ts"), HEADER + dtsLines.join("\n") + "\n");

  /* The manifest lists the public components; the sources are the truth for
     what ships. Report any difference either way. */
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
  const listed = new Set((manifest.components || []).map((c) => c.name));
  const exported = new Set([...owners.keys()].filter((n) => !INTERNAL.has(n)));
  for (const n of exported) if (!listed.has(n)) warn(`${n} (${owners.get(n)}) is exported but not in system/manifest.json`);
  for (const n of listed) if (!exported.has(n)) warn(`${n} is in system/manifest.json but no source exports it`);

  for (const w of warnings) console.warn(`warning: ${w}`);
  if (dir !== OUT) {
    console.log(`build-package: ${files.length} files, ${exported.size} exports, ${modules.filter((m) => m.hasDts).length} declarations -> ${path.relative(ROOT, dir)}/`);
    return;
  }
  const styles = buildStyles(warn);
  const configureBytes = buildConfigureCore();

  console.log(
    `build-package: ${files.length} files (${clientCount} "use client"), ${exported.size} exports, ${modules.filter((m) => m.hasDts).length} declarations -> ${path.relative(ROOT, dir)}/` +
      (warnings.length ? ` (${warnings.length} warning${warnings.length === 1 ? "" : "s"})` : ""),
  );
  console.log(
    `build-package: ${styles.files} stylesheets inlined -> ${path.relative(ROOT, STYLES_OUT)} (${styles.bytes} bytes)` +
      `; ${styles.externals.length} external @import -> ${path.relative(ROOT, FONTS_OUT)}`,
  );
  console.log(`build-package: Configure core (${configureBytes} bytes) -> ${path.relative(ROOT, CONFIGURE_OUT)}`);
}

export { rewriteJsxSpecifiers, collectExports, needsClient, undeclaredComponents };

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const at = process.argv.indexOf("--out");
  main(at > 0 && process.argv[at + 1] ? path.resolve(process.argv[at + 1]) : OUT);
}
