#!/usr/bin/env node
/* Builds the installable ESM package of the components into dist/react/.

     node tools/build-package.mjs

   What it writes (dist/ is gitignored, so none of this is committed):

     dist/react/<group>/<Name>.js     each system/components/<group>/<Name>.jsx,
                                      compiled with the same Babel setup as
                                      tools/build-bundle.mjs. It stays an ES
                                      module that does `import React from
                                      "react"`, so React is the consumer's.
     dist/react/<group>/<Name>.d.ts   the hand-written declarations, copied
     dist/react/index.js              re-exports every export of every file
     dist/react/index.d.ts            re-exports every .d.ts

   Relative import specifiers ending in .jsx are rewritten to .js by a small
   Babel plugin, in the compiled code and in the declarations alike. The
   exports come from each source's AST and are cross-checked against
   system/manifest.json; a difference is a warning, not a failure.

   system/components/lib (vendored React), bundle.js, bundle.css and the .md
   files are not part of the package. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { transformSync } from "@babel/core";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "system", "components");
const OUT = path.join(ROOT, "dist", "react");
const MANIFEST = path.join(ROOT, "system", "manifest.json");

const REACT = [["@babel/preset-react", { runtime: "classic" }]];
const HEADER = "/* Generated by tools/build-package.mjs from system/components. Do not edit. */\n";

/* Rewrites "./X.jsx" and "../g/X.jsx" to ".js" wherever a module specifier
   appears. Each rewrite is reported through onRewrite, so a caller that wants
   the original text untouched can splice by position instead of reprinting. */
function rewriteJsxSpecifiers(onRewrite = () => {}) {
  const fix = (lit) => {
    if (!lit || typeof lit.value !== "string") return;
    const v = lit.value;
    if (!/^\.\.?\//.test(v) || !v.endsWith(".jsx")) return;
    const next = v.slice(0, -".jsx".length) + ".js";
    onRewrite(lit, next);
    lit.value = next;
    if (lit.extra) lit.extra = { ...lit.extra, rawValue: next, raw: JSON.stringify(next) };
  };
  return () => ({
    name: "rewrite-jsx-specifiers",
    visitor: {
      "ImportDeclaration|ExportNamedDeclaration|ExportAllDeclaration"(p) {
        fix(p.node.source);
      },
      CallExpression(p) {
        if (p.node.callee.type === "Import" && p.node.arguments[0]?.type === "StringLiteral") fix(p.node.arguments[0]);
      },
      ImportExpression(p) {
        if (p.node.source?.type === "StringLiteral") fix(p.node.source);
      },
      TSImportType(p) {
        /* Babel 8 calls it source; Babel 7 wrapped it in argument. */
        const arg = p.node.source ?? p.node.argument;
        fix(arg?.type === "TSLiteralType" ? arg.literal : arg);
      },
      TSExternalModuleReference(p) {
        fix(p.node.expression);
      },
    },
  });
}

/* Collects the names a module exports, and whether it has a default export. */
function collectExports(into) {
  return () => ({
    name: "collect-exports",
    visitor: {
      ExportNamedDeclaration(p) {
        const { declaration: d, specifiers } = p.node;
        if (d) {
          if (d.type === "VariableDeclaration") for (const v of d.declarations) into.names.push(...idsOf(v.id));
          else if (d.id) into.names.push(d.id.name);
        }
        for (const s of specifiers) if (s.exported) into.names.push(s.exported.name ?? s.exported.value);
      },
      ExportDefaultDeclaration() {
        into.hasDefault = true;
      },
      ExportAllDeclaration(p) {
        into.starFrom.push(p.node.source.value);
      },
    },
  });
}

function idsOf(pattern) {
  if (!pattern) return [];
  switch (pattern.type) {
    case "Identifier": return [pattern.name];
    case "ObjectPattern": return pattern.properties.flatMap((pr) => idsOf(pr.type === "RestElement" ? pr.argument : pr.value));
    case "ArrayPattern": return pattern.elements.flatMap(idsOf);
    case "AssignmentPattern": return idsOf(pattern.left);
    case "RestElement": return idsOf(pattern.argument);
    default: return [];
  }
}

/* Every .jsx under system/components/<group>/, skipping the vendored lib. */
function sourceFiles() {
  const out = [];
  for (const group of fs.readdirSync(SRC, { withFileTypes: true })) {
    if (!group.isDirectory() || group.name === "lib") continue;
    for (const f of fs.readdirSync(path.join(SRC, group.name))) {
      if (f.endsWith(".jsx")) out.push(`${group.name}/${f}`);
    }
  }
  return out.sort();
}

function compileSource(rel) {
  const src = fs.readFileSync(path.join(SRC, rel), "utf8");
  const exp = { names: [], hasDefault: false, starFrom: [] };
  const code = transformSync(src, {
    filename: path.join(SRC, rel),
    presets: REACT,
    plugins: [rewriteJsxSpecifiers(), collectExports(exp)],
    configFile: false,
    babelrc: false,
    comments: true,
    sourceType: "module",
  }).code;
  return { code, exp };
}

/* Declarations are copied byte for byte except for the specifiers the plugin
   rewrites, which are spliced in by position, so JSDoc and layout survive. */
function copyDeclaration(rel) {
  const src = fs.readFileSync(path.join(SRC, rel), "utf8");
  const edits = [];
  const exp = { names: [], hasDefault: false, starFrom: [] };
  transformSync(src, {
    filename: path.join(SRC, rel),
    parserOpts: { plugins: [["typescript", { dts: true }]] },
    plugins: [
      rewriteJsxSpecifiers((lit, next) => {
        const q = src[lit.start];
        edits.push([lit.start, lit.end, q + next + q]);
      }),
      collectExports(exp),
    ],
    configFile: false,
    babelrc: false,
    code: false,
    sourceType: "module",
  });
  let out = src;
  for (const [s, e, text] of edits.sort((a, b) => b[0] - a[0])) out = out.slice(0, s) + text + out.slice(e);
  return { code: out, exp, rewrites: edits.length };
}

function main() {
  const warnings = [];
  const warn = (msg) => warnings.push(msg);

  fs.rmSync(OUT, { recursive: true, force: true });

  const files = sourceFiles();
  const owners = new Map();
  const modules = [];

  for (const rel of files) {
    const base = rel.slice(0, -".jsx".length);
    const { code, exp } = compileSource(rel);
    if (exp.hasDefault) warn(`${rel}: has a default export, which index.js does not re-export`);
    if (exp.starFrom.length) warn(`${rel}: has export * from ${exp.starFrom.join(", ")}, which index.js does not follow`);
    for (const n of exp.names) {
      if (owners.has(n)) warn(`${n} is exported by both ${owners.get(n)} and ${rel}; index.js keeps the first`);
      else owners.set(n, rel);
    }

    fs.mkdirSync(path.dirname(path.join(OUT, base)), { recursive: true });
    fs.writeFileSync(path.join(OUT, `${base}.js`), HEADER + code + "\n");

    const dts = `${base}.d.ts`;
    let declared = null;
    if (fs.existsSync(path.join(SRC, dts))) {
      const d = copyDeclaration(dts);
      fs.writeFileSync(path.join(OUT, dts), d.code);
      declared = new Set(d.exp.names);
    } else {
      warn(`${rel}: no ${path.basename(dts)} beside it`);
    }
    for (const n of exp.names) {
      if (declared && !declared.has(n)) warn(`${n} (${rel}) is exported at runtime but not declared in ${path.basename(dts)}`);
    }
    modules.push({ base, names: exp.names.filter((n) => owners.get(n) === rel), hasDts: !!declared });
  }

  const js = modules
    .filter((m) => m.names.length)
    .map((m) => `export { ${m.names.join(", ")} } from "./${m.base}.js";`);
  fs.writeFileSync(path.join(OUT, "index.js"), HEADER + js.join("\n") + "\n");

  const dtsLines = modules.filter((m) => m.hasDts).map((m) => `export * from "./${m.base}.js";`);
  fs.writeFileSync(path.join(OUT, "index.d.ts"), HEADER + dtsLines.join("\n") + "\n");

  /* The manifest lists the public components; the sources are the truth for
     what ships. Report any difference either way. */
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, "utf8"));
  const listed = new Set((manifest.components || []).map((c) => c.name));
  const exported = new Set(owners.keys());
  for (const n of exported) if (!listed.has(n)) warn(`${n} (${owners.get(n)}) is exported but not in system/manifest.json`);
  for (const n of listed) if (!exported.has(n)) warn(`${n} is in system/manifest.json but no source exports it`);

  for (const w of warnings) console.warn(`warning: ${w}`);
  console.log(
    `build-package: ${files.length} files, ${exported.size} exports, ${modules.filter((m) => m.hasDts).length} declarations -> ${path.relative(ROOT, OUT)}/` +
      (warnings.length ? ` (${warnings.length} warning${warnings.length === 1 ? "" : "s"})` : ""),
  );
}

export { rewriteJsxSpecifiers, collectExports };

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
