/* Bundles the builder's modules (assets/builder/) into assets/builder.js, the
   one script builder.html loads. The output is generated: edit the modules.
   --check fails if the committed bundle isn't what the modules build to. */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { canvasIcons } from "./canvas-icons.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "assets/builder.js");
const check = process.argv.includes("--check");

const result = await build({
  entryPoints: [path.join(ROOT, "assets/builder/main.js")],
  bundle: true,
  write: false,
  format: "iife",
  target: ["safari16.4", "chrome111", "firefox113"],
  charset: "utf8",
  legalComments: "none",
  logLevel: "silent",
  /* The canvas icons the builder uses, from assets/builder/icons, in place
     of the stand-in module there (see tools/canvas-icons.mjs). */
  plugins: [{
    name: "canvas-icons",
    setup(b) {
      b.onLoad({ filter: /[\\/]builder[\\/]icons[\\/]canvas-icons\.js$/ }, () => {
        const icons = canvasIcons(ROOT);
        return { contents: "export var CI_USE = " + JSON.stringify(icons.use) + ";\nexport var CI_MARKUP = " + JSON.stringify(icons.markup) + ";\nexport var CI_CSS = " + JSON.stringify(icons.css) + ";\n", loader: "js",
          watchFiles: [path.join(ROOT, "assets/builder/icons/use.json")] };
      });
    },
  }],
  /* Strict, as the modules are: a write to a frozen document throws. */
  banner: { js: "/* GENERATED by tools/build-builder.mjs from assets/builder/. Do not edit: change the modules and run npm run build. */\n\"use strict\";" },
});
const code = result.outputFiles[0].text;
const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";

if (check) {
  if (current !== code) {
    console.error("builder: assets/builder.js is out of date. Run npm run build and commit it.");
    process.exit(1);
  }
  console.log("builder bundle is current");
} else if (current !== code) {
  fs.writeFileSync(OUT, code);
  console.log("builder: wrote assets/builder.js (" + Math.round(code.length / 1024) + " KB) from assets/builder/");
} else console.log("builder: assets/builder.js is current");
